### ISSUE TITLE
Issue with Configuarable 3.2.6 and Neruina 3.0.3 on Fabric 1.21.1

### ISSUE THREAD

**Issue by suerion** [Bawnorton/Configurable#19]
Hey, after your update to 3.2.6, i had tried to disable again Neruina on client, but after this, it Timeout all players on Joining. 

Adding Neruina back on the client, it does work without issues

Debug disconnect log
https://mclo.gs/3XNVehu

**Comment by Bawnorton** [comment]
Try updating to configurable 3.2.7 on both clients and the server. That should fix the problem 
Close if so

**Comment by suerion** [comment]
Hey, had no time to test, today i had an maintenance sheduled of our servers. :)

**Comment by suerion** [comment]
@Bawnorton hey, 3.2.7 does not fix the issue, if neruina is on client, it does work if not, it disconnect me from server

https://mclo.gs/0MH0qNW

**Comment by Bawnorton** [comment]
This is a very annoying bug to fix because I can't seem to reproduce it. I'll try something else and let you know when it's published

**Comment by Bawnorton** [comment]
@suerion Try updating configurable to 3.2.8. I think I figured out what was going wrong

**Comment by suerion** [comment]
@Bawnorton will test today, and come back to you :)

**Comment by suerion** [comment]
on 1.21.1 it work :),
